### ISSUE TITLE
Problem while trying to build your image

### ISSUE THREAD

**Issue by remyleone** [tmaier/scaleway-gitlab-runner#1]
I've tried to build your image and stumbled upon the following problem:

```
# sieben @ sieben-macbook in ~/workspace/scaleway-gitlab-runner on git:master o [9:53:28]
$ make shell
wget -qO - http://j.mp/scw-builder | bash
make: *** No rule to make target `shell'.  Stop.
```

**Comment by remyleone** [comment]
Could it be possible to add additional checks to ensure that the environment is correct before trying to build the image?

**Comment by tmaier** [comment]
The `Makefile` is a blunt copy of any `Makefile` at https://github.com/scaleway-community
For example https://github.com/scaleway-community/scaleway-nodejs/blob/master/Makefile

I believe the issue you are having is, that `https://j.mp/scw-builder` does not exist anymore.

It has been deleted with the following commit: https://github.com/scaleway/image-tools/commit/e0e283202fd9bc0a83f05fddbf632e9969af8a97

How should the `Makefile` look like now?

**Comment by remyleone** [comment]
I think @superseed could help us understand where to go from here.
